def build_review_prompt(code: str) -> str:
    return f"""
You are a software engineer performing a code review.

Review the following Python code and write a concise review comment.
Keep in mind that the code you will see is only a snippet of the overall file, and maybe even function, so avoid making assumptions about the completude of the code and focus on what is presented.
Focus on:
- correctness
- readability
- maintainability
- potential issues or improvements

Do not rewrite the code.
Do not mention that this review was generated by an AI.

Python code:
{code}
""".strip()
